<a href="https://colab.research.google.com/github/KwonSohee0620/HUFS_Capstone_Project_DATA/blob/main/insta_processing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install pandas
!pip install numpy

Requirement already satisfied: pandas in /usr/local/lib/python3.7/dist-packages (1.3.5)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.7/dist-packages (from pandas) (2022.1)
Requirement already satisfied: numpy>=1.17.3 in /usr/local/lib/python3.7/dist-packages (from pandas) (1.21.6)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.7.3->pandas) (1.15.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.7/dist-packages (1.21.6)

In [ ]:
import pandas as pd

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
f = pd.read_csv('/content/drive/Shareddrives/캡스톤summa/데이터팀/트렌드.csv')
f.columns = ['tags', 'date', 'likes'] #칼럼 지정

In [ ]:
f = f.drop_duplicates('tags', keep='last')  #tags 리스트 중복 제거
display(f)

                                                   tags       date  likes
7     ['#갸루피스', '#mz세대', '#사진', '#포즈', '#트렌드', '#짤',...   2022.5.2  1,494
9     ['#피스', '#피스티클', '#트렌드', '#투자', '#패션', '#명품', ...   2022.5.9      0
12    ['#미니멀', '#apple', '#스티브잡스', '#시간', '#여유', '#미...   2022.5.9    976
13    ['#블루독', '#여름', '#육아소통', '#맞팔해요', '#육아스타그램', '...   2022.5.9      2
14    ['#네이처하우징', '#이룸건축', '#인테리어', '#트렌드', '#식탁', '...   2022.5.9      2
...                                                 ...        ...    ...
1265  ['#가나초콜릿하우스', '#성수동', '#가나초콜릿', '#팝업스토어', '#성수...   2022.5.9    250
1266  ['#웃음', '#유머', '#감동', '#이슈', '#트렌드', '#킬링타임', ...  2022.4.17      0
1267  ['#역곡', '#역곡미용실', '#부천', '#부ᄎ...   2022.4.4    849
1268  ['#빵빵터짐', '#웃어요', '#유머짤', '#웃음지뢰', '#육아웹툰', '#...  2022.4.21  1,173
1269  ['#빙그레', '#쟈키쟈키돈마호크', '#맛있더맛있', '#트렌드', '#출시',...   2022.5.9      5

[825 rows x 3 columns]

In [ ]:
f['likes'] = f['likes'].str.replace(pat=',', repl = r'') #','문자 제거
f['likes'] = f['likes'].astype(int) #int로 변환

In [ ]:
idx = f[f['likes'] < 10].index  #좋아요 수 10이하 제거
f = f.drop(idx)
display(f)

                                                   tags       date  likes
7     ['#갸루피스', '#mz세대', '#사진', '#포즈', '#트렌드', '#짤',...   2022.5.2   1494
12    ['#미니멀', '#apple', '#스티브잡스', '#시간', '#여유', '#미...   2022.5.9    976
16    ['#미니쉬발몽스파', '#바라는네일', '#딥포커스검안센터', '#미니쉬라운지청담...   2022.5.9    874
17             ['#엄마는예뻤다', '#천안엄마', '#닥터스군단', '#미니쉬칼럼']   2022.5.9    859
30                                ['#스튜디오킨조', '#알잘딱깔센']   2022.5.9     33
...                                                 ...        ...    ...
1263  ['#트렌드', '#소셜트렌드', '#디지털트렌드', '#캠페인', '#브랜딩', ...  2022.4.19    892
1264  ['#아이유허쉬컷', '#허쉬컷', '#아이유', '#가나다라', '#박재범', '...  2022.4.22   1378
1265  ['#가나초콜릿하우스', '#성수동', '#가나초콜릿', '#팝업스토어', '#성수...   2022.5.9    250
1267  ['#역곡', '#역곡미용실', '#부천', '#부ᄎ...   2022.4.4    849
1268  ['#빵빵터짐', '#웃어요', '#유머짤', '#웃음지뢰', '#육아웹툰', '#...  2022.4.21   1173

[508 rows x 3 columns]

In [ ]:
idx = f[f['likes'] > 1000].index